--------------------------------------------------------
--  DDL for Table DATABASECHANGELOG
--------------------------------------------------------

  CREATE TABLE "HR"."DATABASECHANGELOG" 
   (	"ID" VARCHAR2(255 BYTE), 
	"AUTHOR" VARCHAR2(255 BYTE), 
	"FILENAME" VARCHAR2(255 BYTE), 
	"DATEEXECUTED" TIMESTAMP (6), 
	"ORDEREXECUTED" NUMBER(*,0), 
	"EXECTYPE" VARCHAR2(10 BYTE), 
	"MD5SUM" VARCHAR2(35 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"COMMENTS" VARCHAR2(255 BYTE), 
	"TAG" VARCHAR2(255 BYTE), 
	"LIQUIBASE" VARCHAR2(20 BYTE), 
	"CONTEXTS" VARCHAR2(255 BYTE), 
	"LABELS" VARCHAR2(255 BYTE), 
	"DEPLOYMENT_ID" VARCHAR2(10 BYTE)
   ) ;
